version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: blog_postgres_db
    environment:
      POSTGRES_USER: sanya
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: social_blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_backend_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sanya:your_secure_password@db:5432/social_blog
    depends_on:
      - db

# Das hat unten gefehlt! Das sichert deine Datenbank-Daten:
volumes:
  postgres_data:
