events {
    worker_connections 1024;
}

http {
    # Настройка маршрутов для запросов
    server {
        listen 80;
        server_name localhost;

        # 1. Направляем запросы авторизации на Auth-Service
        location /api/auth/ {
            proxy_pass http://auth_microservice:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Направляем запросы задач на Task-Service
        location /api/tasks/ {
            proxy_pass http://task_microservice:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
